# Generated by Django 6.0.7 on 2026-07-20 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_categ', models.CharField(max_length=8, unique=True)),
                ('libelle_categ', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_article', models.CharField(max_length=8, unique=True)),
                ('libelle_article', models.CharField(max_length=30)),
                ('quantite_stock', models.IntegerField()),
                ('seuil_alerte', models.IntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.categorie')),
            ],
        ),
    ]
