# Generated by Django 6.0.7 on 2026-07-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bloque_jusqu_a',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
