# Generated by Django 6.0.7 on 2026-07-20 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField()),
                ('date_livraison', models.DateField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('TRANSMISE', 'Transmise'), ('EN_PREPARATION', 'En préparation'), ('PREPAREE', 'Préparée'), ('PRETE', 'Prête'), ('LIVREE', 'Livrée')], default='EN_ATTENTE', max_length=15)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.IntegerField()),
                ('quantite_servie', models.IntegerField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.article')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.demande')),
            ],
            options={
                'unique_together': {('demande', 'article')},
            },
        ),
    ]
