# Generated by Django 6.0.7 on 2026-07-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date_livraison',
            field=models.DateField(blank=True, null=True),
        ),
    ]
